name: Run the whole application

on:
  push:
    branches: master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Get your code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # 3️⃣ Install deps
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Create .env.local from the DOTENV secret
      - name: Create .env.local
        run: echo "$DOTENV" > .env.local
        env:
          DOTENV: ${{ secrets.DOTENV }}

      # 5️⃣ Start Backend
      - name: Open venv
        run: venv\Scripts\activate

      - name: Start backend
        run: uvicorn app:app        


      # 5️⃣ Start Frontend
      - name: Open venv
        run: venv\Scripts\activate

      - name: Start backend
        run: npm start        
